### ISSUE TITLE
Multi monitor problem

### ISSUE THREAD

**Issue by orychalk** [luisbocanegra/plasma-wallpaper-effects#1]
Hi,

This is a GREAT effect, I love it 😄.

I don't know if it's a bug or me who can't configure it correctly, but with multiple monitor, I have problems.

When I put the widget on one monitor, the second monitor doesn't apply the effect.

If I put widget on all monitor (one widget by monitor) it's work better, but in some time the effect don't work anymore on one of the monitor.

Same with corner effect.

I use Manjaro with Plasma 6 (Fresh install).

Thanks in advance.

**Comment by luisbocanegra** [comment]
> When I put the widget on one monitor, the second monitor doesn't apply the effect.

This is expected, the widget looks for the wallpaper element in the current screen, not sure if it can go to other screens but most likely it does not. So the solution is as you did, having one widget instance on each screen.

> If I put widget on all monitor (one widget by monitor) it's work better, but in some time the effect don't work anymore on one of the monitor.

Can you be more specific of the behavior you are seeing:
- What you see, what you expected to happen and which situation (or how often if it seems random) this happens
- Which wallpaper plugin are you using (send screenshot of **Right click on desktop** > **Configure Desktop and Wallpaper**)
- What are your settings, please send a screenshot of the widget settings

**Comment by orychalk** [comment]
Thanks for confirming my suspicions for the first answer :)

To answer your questions :
- After multiple additional tests, I can say that it is not random.
- I use the Superpaper application, but I reproduce the phenomenon with other wallpaper plugins, including the one provided by default in Plasma 6.
- This happens in 2 cases, I will explain

I have 2 screens on a desktop PC and on the same graphics card.

Here are some elements of my config:
```
Operating System: Manjaro Linux
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
QtVersion: 6.7.0
Kernel Version: 6.9.0-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel Core i7-7700K CPU @ 4.20GHz
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Monitor 1 on HDMI: 3440x1440@100Hz
Monitor 2 on HDMI: 3440x1440@100Hz
```

**First scenario:**
* When I arrive at the SDDM login, by default SDDM is displayed on both screens.
* When I log in to KDE 6, no problem with blur & corners
* On the other hand, out of habit I force the deactivation of the second screen for SDDM with 
`xrandr --output HDMI-2 --off`
in /usr/share/sddm/scripts/Xsetup
* Like this I have only 1 screen in SDDM and the 2 are automatically activated when I arrive in KDE6.
* Disabling the second screen in SDDM prevents Plasma Wallpaper Effect from working on this second screen once logged in (no blur or rounded corners).
On the first screen it still works fine.
* To make it work on all screens, I found a workaround:
`plasmashell --replace &`



**For the second scenario, it's a bit the same thing.**
I have 2 scripts that turn the second screen off and on when I run them manually.
I don't necessarily need the second screen all the time and above all it saves me electricity.
The script that turns off the second screen:
```
#!/bin/bash
kscreen-doctor output.HDMI-A-2.disable
```

The script that turns the second screen back on:
```
#!/bin/bash
kscreen-doctor output.HDMI-A-2.enable output.HDMI-A-2.mode.3440x1440@100 output.HDMI-A-2.position.0,-1440
```

When I turn the second screen back on, the second screen widget no longer works (No blur or rounded corners).
On the first screen, all work.
So same workaround as in the first case, I run a plasmashell --replace & and everything works again.

These are indeed non-standard cases that most people definitely don't use, but it's part of my daily workflow.

I hope i was clear

Thank in advance.
![Widget](https://github.com/luisbocanegra/plasma-wallpaper-effects/assets/57261547/13b4dc4c-3053-4c95-adb5-e864337ab10e)

**Comment by luisbocanegra** [comment]
Thanks for the very detailed description, I can confirm that disabling and enabling a screen from the **Display Configuration** widget causes effects to stop working on that screen. Will try coming up with a fix soon.

**Comment by luisbocanegra** [comment]
Hi, can you test if the latest change fixes the problem?

Just clone the project and either run ./install.sh or use kpackagetool6:

```sh
git clone https://github.com/luisbocanegra/plasma-wallpaper-effects
cd plasma-wallpaper-effects
./install.sh
```
If you are missing some dependency the install script will fail, in that case run `kpackagetool6 -t Plasma/Applet -u package/` instead. Or, as a last resort, just replace the contents of `package/` into `~/.local/share/plasma/plasmoids/luisbocanegra.desktop.wallpaper.effects/`
Finally, logout/restart and try to reproduce the bug

**Comment by orychalk** [comment]
Hi,
It's work 😄👍
Thanks a lot 😀

**Comment by luisbocanegra** [comment]
You're welcome! Will push a new release to the KDE Store later today. Thanks again for testing

**Comment by luisbocanegra** [comment]
Fixed in https://github.com/luisbocanegra/plasma-wallpaper-effects/releases/tag/v0.1.1
