### ISSUE TITLE
Wallhaven incompatibility

### ISSUE THREAD

**Issue by orychalk** [luisbocanegra/plasma-wallpaper-effects#4]
Hello,

I use the new plug in wallpaper engine Wallhaven [Git](https://github.com/Blacksuan19/plasma-wallpaper-wallhaven-reborn)  [Kde Store](https://www.pling.com/p/2193590/), but : 
- Blur Effect does not work with it.
- Corner effect work.

It works well with the other wallpaper plugins (Wallpaper of the day), blur and corner.

Can you help me ?

Thanks in advance.

**Comment by luisbocanegra** [comment]
Thanks for the report, can confirm the plugin is not working. Will take a look as soon as I can and be back to you with a version to test.

**Comment by luisbocanegra** [comment]
Figured it out, the area to be blurred didn't have a size so the effect wasn't visible.

Sent a patch that makes it work to that project: https://github.com/Blacksuan19/plasma-wallpaper-wallhaven-reborn/pull/4

Can you confirm it works for you too?

**Comment by luisbocanegra** [comment]
Thanks for the confirmation, let's wait for the pull request to be accepted.
